title: UHM Clubhouse
description: 
google_analytics:
show_downloads: false
theme: jekyll-theme-time-machine
github:
  is_project_page: true
  repository_url: https://github.com/uhm-clubhouse/uhm-clubhouse
gems:
  - jekyll-mentions
